language: objective-c
xcode_project: RHObjCExt.xcodeproj
xcode_scheme: RHObjCExtLogicTests
before_install:
  - brew update
    #  - brew install xctool >/dev/null
  - gem update --system
  - gem install cocoapods
  - bundle install
  - pod install
  - xcodebuild -showsdks
script: bundle exec rake run_app_test --trace

